// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt7zpK90Bp9-iTFgglShAMkE5YWNHvwLM',
    appId: '1:920127357533:android:3f3714f11366c8c73003b4',
    messagingSenderId: '920127357533',
    projectId: 'bookshare-8ed63',
    storageBucket: 'bookshare-8ed63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdu-Mz19Sk6PdM9YNWU77sghWd40Qx3Ew',
    appId: '1:920127357533:ios:7c6390a43ff146f53003b4',
    messagingSenderId: '920127357533',
    projectId: 'bookshare-8ed63',
    storageBucket: 'bookshare-8ed63.appspot.com',
    iosClientId: '920127357533-0g9l96hoerlnuc9o9v1o378b1csb7dju.apps.googleusercontent.com',
    iosBundleId: 'c',
  );
}
